# Generated by Django 5.2 on 2025-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_founditem_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_found_images/'),
        ),
    ]
